default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hellorails
  password: Incorrect12*

development:
  adapter: postgresql
  database: hellorails_development
  username: hellorails
  password: Incorrect12*
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: hellorails_test
  username: hellorails
  password: Incorrect12*
  encoding: unicode
  host: localhost
  pool: 5  

production:
  <<: *default
  database: hellorails_production
  username: hellorails
  password: <%= ENV["HELLORAILS_DATABASE_PASSWORD"] %>
